import { z } from "zod";

// Validation schema for a single staff import row
// Note: Password will be auto-generated by the server
export const staffImportRowSchema = z.object({
  email: z.string().email("Invalid email address"),
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  role_ids: z
    .array(z.string().uuid("Invalid role ID"))
    .min(1, "At least one role is required"),
});

export type StaffImportRow = z.infer<typeof staffImportRowSchema>;

// Validation result for a single row
export interface ValidationResult {
  row: number;
  data: StaffImportRow | null;
  isValid: boolean;
  errors: Array<{
    field: string;
    message: string;
  }>;
}

// Column mapping interface
export interface ColumnMapping {
  email: string | null;
  first_name: string | null;
  last_name: string | null;
  role_ids: string[] | null;
}

// Required fields for import
export const REQUIRED_FIELDS = [
  "email",
  "first_name",
  "last_name",
  "role_ids",
] as const;
export type RequiredField = (typeof REQUIRED_FIELDS)[number];

// Excel row data
export interface ExcelRow {
  [key: string]: unknown;
}

// Import summary
export interface ImportSummary {
  total: number;
  valid: number;
  invalid: number;
  validRecords: ValidationResult[];
  invalidRecords: ValidationResult[];
}

// Bulk import request
export interface BulkImportStaffRequest {
  staff: StaffImportRow[];
}

// Bulk import response
export interface BulkImportStaffResponse {
  success: boolean;
  data: {
    imported: number;
    failed: number;
    failedRecords: Array<{
      row: number;
      email: string;
      reason: string;
    }>;
  };
}
