-- FULL Nash purge (STAGING): soft-delete every school on the Nash doc + their
-- leads + contacts (active rows only; already-deleted stay deleted). Reversible.
BEGIN;
CREATE TEMP TABLE _nash_names(name text);
INSERT INTO _nash_names(name) VALUES
('amhlophe high school'),
('bulawayo adventist high school'),
('induna high school'),
('inyanda high school'),
('light house secondary schoool'),
('tennyson hlabangana'),
('buvuma high school'),
('dula secondary school'),
('garanyemba secondary school'),
('j.z moyo high school'),
('kwalu secondary school'),
('lubhangwe high school'),
('lubuze high school'),
('lushonkwe high school'),
('makikuwa secondary school'),
('malungudzi high school'),
('mawabeni high school'),
('mlomotsha secondary school'),
('mqabuko secondary school'),
('msakorokoro secondary school'),
('mzingwane high school'),
('nhwali high school'),
('ntalale high secondary school'),
('sadiwa high school'),
('sibhata secondary school'),
('siwazi high school'),
('solusi adventist high school'),
('tahangana secondary school'),
('tokwana high school'),
('tongwe high school'),
('tshanyaugwe secondary school'),
('valukhalo secondary school'),
('ntalale secondary schools'),
('amr convent high school'),
('bembesi secondary school'),
('chibila adventist secondary school'),
('chinonge secondary school'),
('chipale secondary school'),
('dikili high school'),
('don bosco secondary school'),
('gebhuza high school'),
('george silundika high school'),
('jibajiba secondary school'),
('kapane secondary school'),
('lesedi secondary school'),
('lubu secondary school'),
('lusulu high school'),
('madlelenyoni secondary school'),
('mateme secondary school'),
('mkhosana adventist secondary school'),
('mnondo secondary school'),
('muchesu secondary school'),
('nakaluba secondary'),
('nhlambabaloyi secondary school'),
('nyamandlovu secondary school'),
('rcz manyanda secondary school'),
('saba secondary school'),
('samende secondary school'),
('sawmills secondary school'),
('sinangengwe secondary school'),
('sizinda secondary school'),
('sojini high school'),
('somvubu high school'),
('tame secondary school'),
('zambezi secondary school'),
('bayayi secondary school'),
('bonstead secondary school'),
('chebvute secondary school'),
('chemimwe high school'),
('chibhuku secondary school'),
('chikeya high school'),
('chivona secondary school'),
('chovurach secondary school'),
('chushuku secondary school'),
('defe high school'),
('dorset secondary school'),
('gonawapotera high school'),
('gununyu high school'),
('guruva high school'),
('gwamure high school'),
('havano high school'),
('kaguwe secondary school'),
('mabika high school'),
('maboleni high school'),
('makulambili secondary school'),
('manzinyama secondary school'),
('maringambizi secondary school'),
('mashame secondary school'),
('matabo secondary school'),
('mbovhana secondary school'),
('mbungu secondary school'),
('mbuyanehanda high school'),
('mpadashaya high school'),
('mpandashango high school'),
('mposi high school'),
('mtshingwe platinum high school'),
('musikavanhu secondary school'),
('musume high school'),
('ndlamatulu secondary school'),
('norah secondary school'),
('ntabamhlophe secondary school'),
('ruzengwe secondary school'),
('sawirangwanda secondary school'),
('sibomvu secondary school'),
('sikombingo adventist higgh school'),
('svibe high school'),
('thornhill high school'),
('vubwe high school'),
('vungu secondary school'),
('vurasha high school'),
('vurasha secondary school'),
('vuronga secondary school'),
('zvamagwiro secondary school'),
('zvamanwiro secondary school'),
('zvavashe secondary school'),
('zvomukonde high school'),
('avhunga secondary school'),
('bwanya secondary school'),
('chamasvinga secondary school'),
('charingeno secondary school'),
('chatikobo high school'),
('chatworth secondary school'),
('chekai secondary school'),
('cheninga hiwa secondary school'),
('chesvingo secondary school'),
('chikwirire secondary school'),
('chimbwembwe secondary school'),
('chingele secondary school'),
('chitovo secondary school'),
('chiwanumba high school'),
('chiwanza secondary school'),
('chiwawa sda secondary school'),
('chongogwe high school'),
('danhamombe high school'),
('dengenya secondary school'),
('domborembawa high school'),
('domboshava secondary school'),
('dzoro high school'),
('gutu high school'),
('hebron high school'),
('jaka secondary school'),
('jichidza high school'),
('justin chauke secondary school'),
('m. hugo high school'),
('machingambi high school'),
('madangamombe gvt high school'),
('magura high school'),
('makoni secondary school'),
('masogwe baptist high school'),
('mataruse secondary school'),
('mfula secondary school'),
('mucheke high school'),
('murere secondary school'),
('murere sec school'),
('musenyereku high school'),
('mushaviri secondary school'),
('mushungwa secondary school'),
('mutangi secondary school'),
('nemauku secondary school'),
('nerupiri high school'),
('neshuro high school'),
('ngundu halt high school'),
('nyahombe secondary school'),
('pfungidzo high school'),
('rambakutemwa secondary school'),
('rumizha secondary scchool'),
('rupare high school'),
('rupiri mukosi high school'),
('sabert high school'),
('sagewari secondary school'),
('shindi secondaryvschool'),
('st stanislaus secondary school'),
('tereraire high school'),
('tungamirai high school'),
('wondedzo secondary school'),
('zivezano highschool'),
('makura secondary school'),
('dekeza high school'),
('magudu secondary school'),
('masunda north secondary school'),
('zororai secondary school'),
('allan wilson'),
('domboramusari high'),
('emerald hill'),
('hatcliff high'),
('muguta secondary'),
('mukai high'),
('oriel girls high'),
('warren park high'),
('gweru high'),
('dope high school'),
('nyarumvurwe secondary'),
('mt zonwe secondary'),
('claremonnt secondary'),
('zurara secondary'),
('mhakwe high'),
('nyarwizi secondary'),
('nuatate high schhol'),
('shundure high'),
('gwirundindi high'),
('chikwariro high school'),
('mutsvangwa secondary'),
('marange high school'),
('nyashanu high'),
('zambara secondary'),
('gosho secondary'),
('mudza,iri secondary'),
('tsikada secondary'),
('nyarwidzi secondary'),
('staugustine'),
('bemitiwa secondary school'),
('sherenje secondary school'),
('kandenga secondary'),
('zvembira secondary'),
('bumhira sec'),
('mutepfe secondary'),
('meadowlands'),
('gwidza secondary'),
('rongwe high school'),
('mweyamunene high'),
('shekija secondary'),
('kanyimo secondaey'),
('chapandura secondary'),
('nechikowa secondary'),
('tsindi secondary'),
('chikwakwa secondary'),
('gwebu high'),
('chirinda high'),
('chinyauhwera high school'),
('mwazheta high school'),
('gunura secondary'),
('chikanya high'),
('mazarura high school'),
('gideon mihlanga high'),
('karakwi high'),
('bemutiwa secondary'),
('buhera high school'),
('elisegledhill high'),
('nyamajura secondary'),
('anderson secondary'),
('beatrice high'),
('bosha secondary'),
('chabwino high'),
('chatiza high'),
('chikwidibire secondary'),
('chikwizo secondary'),
('chimukoko secondary'),
('chipfunde secondary'),
('chisambiro secondary'),
('chisangano high'),
('chitepo secondary'),
('chivenga secondary'),
('chiwwashira secondary'),
('classic academy'),
('dombodzvuku secondary'),
('domboramavara'),
('eagle secondary'),
('glenforest dev centre'),
('goromonzi secondary'),
('govere secondary'),
('gozi secondary'),
('guruuswa secondary'),
('guyu secondary'),
('hanwa secondary'),
('holy spirit ruzane secondary'),
('katsande secondary'),
('kotwa high'),
('liebenberg high'),
('madzivira range high'),
('mahusvu secondary'),
('manyene secondary'),
('mapombo high'),
('marikopo secondary'),
('masasa secodary'),
('mhari high'),
('morris secondary'),
('murehwa district'),
('musanhi high'),
('mutanhaurwa'),
('muvande secondary'),
('naglehouse'),
('nyahuni adventist high'),
('nyamapanda seconary'),
('nyamashato secondary'),
('nyamukoho secondary'),
('nyanitepo'),
('parirewa high'),
('runyararo seconary'),
('rwamba secondary'),
('sadza secondary'),
('seke district'),
('shamu secondary'),
('st hughs ushewekunzi sec'),
('st marys makanda sec'),
('st pauls sango secondary'),
('st peter makwarimba secondary'),
('st vincent secondary'),
('karigamombe secondary'),
('st charles secondary'),
('kudzanai secondary'),
('kardi high'),
('chiedza karoi high'),
('mauya high'),
('mungari secondary'),
('urume secondary'),
('zebra downs secondary'),
('marere secondary'),
('lynx secondary'),
('royden secondary'),
('mutsonzowa secondary'),
('rimuka 2 high'),
('dalny high'),
('chinove secondary'),
('nyavika secondary'),
('ponderosa secondary'),
('masau high'),
('machaga high'),
('vimbai high'),
('nyamatani secondary'),
('mopani park secondary'),
('maysma secondary'),
('zowa high'),
('trelawney secondary'),
('mucheki secondary'),
('ngezi barracks high'),
('denderedzi secondary'),
('tawstock secondary'),
('sanyati government high'),
('junction adventist'),
('magogi secondary'),
('inyati secondary'),
('david guzuzu high'),
('nyatsanga secondary'),
('chifundi secindary'),
('masiyarwa high'),
('kazangarare high'),
('chipfuko secondary'),
('amevu secondary'),
('bungwe srcondary'),
('caesar mine secondary'),
('chamutukutu secondary'),
('chawanda high'),
('chidikamwadzi secondary'),
('chihuri'),
('chimurenga 3 secondary'),
('chirisori secondary'),
('gee jay secondary'),
('gwangwava high'),
('kadzi secondary'),
('kugotsi secondary'),
('kundayi high'),
('machadondwa secondary'),
('machanga high'),
('mahuwe high'),
('marongwe secondary'),
('mbari secondary'),
('mhokore secondary'),
('mupfurudzi secondary'),
('mutondwe school'),
('mvurwi high'),
('nyamuseve secodary'),
('nyandoro secondary'),
('nyanhunzi seconadry'),
('soma secondary'),
('tabex secondary'),
('wadzanai high'),
('wayerera high'),
('whaddon chase secondary');
DROP TABLE IF EXISTS nash_full_undo_schools;
DROP TABLE IF EXISTS nash_full_undo_leads;
DROP TABLE IF EXISTS nash_full_undo_contacts;
CREATE TABLE nash_full_undo_schools AS
  SELECT id FROM schools WHERE deleted_at IS NULL AND lower(trim(name)) IN (SELECT name FROM _nash_names);
CREATE TABLE nash_full_undo_leads AS
  SELECT id FROM leads WHERE deleted_at IS NULL AND school_id IN (SELECT id FROM nash_full_undo_schools);
CREATE TABLE nash_full_undo_contacts AS
  SELECT c.id FROM contacts c JOIN schools s ON s.id = c.school_id
   WHERE c.deleted_at IS NULL AND lower(trim(s.name)) IN (SELECT name FROM _nash_names);
UPDATE leads    SET deleted_at = NOW() WHERE id IN (SELECT id FROM nash_full_undo_leads);
UPDATE contacts SET deleted_at = NOW() WHERE id IN (SELECT id FROM nash_full_undo_contacts);
UPDATE schools  SET deleted_at = NOW() WHERE id IN (SELECT id FROM nash_full_undo_schools);
SELECT (SELECT COUNT(*) FROM nash_full_undo_schools) AS schools_removed,
       (SELECT COUNT(*) FROM nash_full_undo_leads)   AS leads_removed,
       (SELECT COUNT(*) FROM nash_full_undo_contacts) AS contacts_removed;
COMMIT;